# Generated by Django 4.0.5 on 2022-07-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='updated_at',
        ),
    ]
